### ISSUE TITLE
Update Blog style

### ISSUE THREAD

**Issue by caspii** [caspii/kittysplit-blog#3]
The blog still uses the old CSS.

Pleas change it to use the new styles. It's probably easiest to copy all the styles into the blog repo.

You'll have to get jekyll up and running, which is a cool tool.

Any questiosn, ask me!

**Comment by Youngbloodr77** [comment]
Branch and changes have been made.

**Comment by caspii** [comment]
Looks great.

However, one thing that won't work:
```<link href="http://www.kittysplit.com/css/app.css?vsn=129D7C9" rel="stylesheet" type="text/css">```

The ``?vsn=129D7C9`` is a cache-busting measure, and will change the next time Kittysplit is deployed. I'm going to remove it completely, should work then

**Comment by Youngbloodr77** [comment]
Yeah sure.

**Comment by caspii** [comment]
One more thing: could you make the font-weight lighter to look more in line with http://www.kittysplit.com/help?

**Comment by Youngbloodr77** [comment]
Done. Had to load the Google font seeing the @import() didn't deliver it
through the stylesheet.

**Comment by caspii** [comment]
Cool, thanks. You shouldn't be using @import anyway, see here:
http://stackoverflow.com/questions/7199364/import-vs-link





On Mon, Jun 1, 2015 at 8:35 AM, Matthew Henderson <notifications@github.com>
wrote:

> Done. Had to load the Google font seeing the @import() didn't deliver it
> through the stylesheet.
>
> On Sun, May 31, 2015 at 7:29 PM, Caspar <notifications@github.com> wrote:
>
> > One more thing: could you make the font-weight lighter to look more in
> > line with http://www.kittysplit.com/help?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caspii/kittysplit-blog/issues/3#issuecomment-107226089>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caspii/kittysplit-blog/issues/3#issuecomment-107322327>
> .
>



-- 
Caspar +491635561322 Berlin, Germany

**Comment by Youngbloodr77** [comment]
Good to know. You can be the one to tell the boys ;-)

**Comment by caspii** [comment]
Don't need to! The blog is still hosted on Google App Engine along with the
old Kittysplit.

On Mon, Jun 1, 2015 at 8:59 AM, Matthew Henderson <notifications@github.com>
wrote:

> Good to know. You can be the one to tell the boys ;-)
>
>
> On Mon, Jun 1, 2015 at 8:56 AM, Caspar <notifications@github.com> wrote:
>
> > Cool, thanks. You shouldn't be using @import anyway, see here:
> > http://stackoverflow.com/questions/7199364/import-vs-link
> >
> >
> >
> >
> >
> > On Mon, Jun 1, 2015 at 8:35 AM, Matthew Henderson <
> > notifications@github.com>
> > wrote:
> >
> >
> > > Done. Had to load the Google font seeing the @import() didn't deliver
> it
> > > through the stylesheet.
> > >
> > > On Sun, May 31, 2015 at 7:29 PM, Caspar <notifications@github.com>
> > wrote:
> > >
> > > > One more thing: could you make the font-weight lighter to look more
> in
> > > > line with http://www.kittysplit.com/help?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/caspii/kittysplit-blog/issues/3#issuecomment-107226089>
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/caspii/kittysplit-blog/issues/3#issuecomment-107322327>
> > > .
> > >
> >
> >
> >
> > --
> > Caspar +491635561322 Berlin, Germany
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caspii/kittysplit-blog/issues/3#issuecomment-107329525>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caspii/kittysplit-blog/issues/3#issuecomment-107330355>
> .
>



-- 
Caspar +491635561322 Berlin, Germany

**Comment by caspii** [comment]
Finally deployed this.
